import type { Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { CartProvider } from '@/lib/cart-context'
import './globals.css'
import { Toaster } from 'sonner'

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`antialiased`}>
          <CartProvider>
            {children}
            <Toaster />
          </CartProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}